# Mathematical functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## Trigonometric functions

Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [7]:
x = np.array([0., 1., 30, 90])
print(f'sine of x : {np.sin(x)}')
print(f'cosine of x : {np.cos(x)}')
print(f'tangent of x : {np.tan(x)}')


sine of x : [ 0.          0.84147098 -0.98803162  0.89399666]
cosine of x : [ 1.          0.54030231  0.15425145 -0.44807362]
tangent of x : [ 0.          1.55740772 -6.4053312  -1.99520041]


Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [9]:
x = np.array([-1., 0, 1.])
print(f'inverse sine of x : {np.arcsin()}')
print(f'inverse cosine of x : {np.arccos(x)}')
print(f'inverse tangent of x : {np.arctan(x)}')

inverse sine of x : [-1.57079633  0.          1.57079633]
inverse cosine of x : [3.14159265 1.57079633 0.        ]
inverse tangent of x : [-0.78539816  0.          0.78539816]


Q3. Convert angles from radians to degrees.

In [11]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
print(f'Angles from radians to degrees of x : {np.degrees(x)}')

Angles from radians to degrees of x : [-180.  -90.   90.  180.]


Q4. Convert angles from degrees to radians.

In [16]:
x = np.array([-180.,  -90.,   90.,  180.])
print(f'Angles from degrees to radians of x : {np.deg2rad(x)}')

Angles from degrees to radians of x : [-3.14159265 -1.57079633  1.57079633  3.14159265]


## Hyperbolic functions

Q5. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.

In [17]:
x = np.array([-1., 0, 1.])
print(f'hyperbolic sine of x : {np.sinh(x)}')
print(f'hyperbolic cosine of x : {np.cosh(x)}')
print(f'hyperbolic tangent of x : {np.tanh(x)}')

hyperbolic sine of x : [-1.17520119  0.          1.17520119]
hyperbolic cosine of x : [1.54308063 1.         1.54308063]
hyperbolic tangent of x : [-0.76159416  0.          0.76159416]


## Rounding

Q6. Predict the results of these, paying attention to the difference among the family functions.

In [19]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x)
out2 = np.floor(x)
out3 = np.ceil(x)
out4 = np.trunc(x)
out5 = [round(elem) for elem in x]

print (out1)
print (out2)
print (out3)
print (out4)
print (out5)


[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]
[2, 2, 2, 3, -2, -2, -3]


Q7. Implement out5 in the above question using numpy.

In [21]:
out5 = [round(elem) for elem in x]
out5

[2, 2, 2, 3, -2, -2, -3]

## Sums, products, differences

Q8. Predict the results of these.

In [23]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = [np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "",
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "",
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),
        "",
        np.cumprod(x),
        np.cumprod(x, axis=0),
        np.cumprod(x, axis=1),
        "",
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]
for i in outs:
    print(i)


36
[ 6  8 10 12]
[[10]
 [26]]

40320
[ 5 12 21 32]
[[  24]
 [1680]]

[ 1  3  6 10 15 21 28 36]
[[ 1  2  3  4]
 [ 6  8 10 12]]
[[ 1  3  6 10]
 [ 5 11 18 26]]

[    1     2     6    24   120   720  5040 40320]
[[ 1  2  3  4]
 [ 5 12 21 32]]
[[   1    2    6   24]
 [   5   30  210 1680]]

1
[1 2 3 4]
[[1]
 [5]]

8
[5 6 7 8]
[[4]
 [8]]

4.5
[3. 4. 5. 6.]
[[2.5]
 [6.5]]


Q9. Calculate the difference between neighboring elements, element-wise.

In [25]:
x = np.array([1, 2, 4, 7, 0])
print(f'the difference between neighboring elements : {np.diff(x)}')

the difference between neighboring elements : [ 1  2  3 -7]


Q10. Calculate the difference between neighboring elements, element-wise, and
prepend [0, 0] and append[100] to it.

In [34]:
x = np.array([1, 2, 4, 7, 0])
print(f'difference between neighboring elements, element-wise, and prepend [0, 0] and append[100] to it array says :\n{np.diff(x,prepend=[0,0],append=[100])}')

difference between neighboring elements, element-wise, and prepend [0, 0] and append[100] to it array says :
[  0   1   1   2   3  -7 100]


Q11. Return the cross product of x and y.

In [38]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(f'cross product of x and y : {np.cross(x,y)}')

cross product of x and y : [-3  6 -3]


## Exponents and logarithms

Q12. Compute $e^x$, element-wise.

In [40]:
x = np.array([1., 2., 3.], np.float32)
print(f'e^x of x : {np.exp(x)}')

e^x of x : [ 2.718282   7.3890557 20.085537 ]


Q13. Calculate exp(x) - 1 for all elements in x.

In [42]:
x = np.array([1., 2., 3.], np.float32)
print(f'exp(x)-1 : {np.exp(x)-1}')

exp(x)-1 : [ 1.718282   6.3890557 19.085537 ]


Q14. Calculate $2^p$ for all p in x.

In [44]:
x = np.array([1., 2., 3.], np.float32)
res = [2**p for p in x]
print(f'2^p for all element of x : {res}')

2^p for all element of x : [2.0, 4.0, 8.0]


Q15. Compute natural, base 10, and base 2 logarithms of x element-wise.

In [49]:
x = np.array([1, np.e, np.e**2])
print(f'Natural log of x : {np.log(x)}')
print(f'log base10 of x : {np.log10(x)}')
print(f'log base2 of x : {np.log2(x)}')

Natural log of x : [0. 1. 2.]
log base10 of x : [0.         0.43429448 0.86858896]
log base2 of x : [0.         1.44269504 2.88539008]


Q16. Compute the natural logarithm of one plus each element in x in floating-point accuracy.

In [54]:
x = np.array([1e-99, 1e-100])
print(f' natural logarithm of one plus each element in x in floating-point accuracy : {np.log1p(x)}')

 natural logarithm of one plus each element in x in floating-point accuracy : [1.e-099 1.e-100]


## Floating point routines

Q17. Return element-wise True where signbit is set.

In [56]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])
print(np.signbit(x))

[ True  True  True False False False False]


Q18. Change the sign of x to that of y, element-wise.

In [62]:
x = np.array([-1, 0, 1])
y = -1.1
print(f'Change the sign of x to that of y, element-wise array says :{np.sign(y)*np.abs(x)}')

Change the sign of x to that of y, element-wise array says :[-1. -0. -1.]


## Arithmetic operations

Q19. Add x and y element-wise.

In [64]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
print(f'add of x and y element wise : {np.add(x,y)}')

add of x and y element wise : [0 0 0]


Q20. Subtract y from x element-wise.

In [65]:
x = np.array([3, 4, 5])
y = np.array(3)
print(f'substraction of x and y element wise : {np.subtract(x,y)}')

substraction of x and y element wise : [0 1 2]


Q21. Multiply x by y element-wise.

In [66]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
print(f'MUl of x and y element wise : {np.multiply(x,y)}')

MUl of x and y element wise : [ 3  0 -5]


Q22. Divide x by y element-wise in two different ways.

In [70]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
print(f'division of x and y element wise : {np.divide(x,y)}')
print(x//y)

division of x and y element wise : [3.         2.         1.66666667]
[3. 2. 1.]


Q23. Compute numerical negative value of x, element-wise.

In [72]:
x = np.array([1, -1])
print(f'numerical negative value of x:{np.negative(x)}')

numerical negative value of x:[-1  1]


Q24. Compute the reciprocal of x, element-wise.

In [73]:
x = np.array([1., 2., .2])
print(f'reciprocal of x :{np.reciprocal(x)}')

reciprocal of x :[1.  0.5 5. ]


Q25. Compute $x^y$, element-wise.

In [79]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
print(f'x^y :\n{np.power(x,y)}')

x^y :
[[ 1  4]
 [ 3 16]]


Q26. Compute the remainder of x / y element-wise in two different ways.

In [85]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
print(np.remainder(x,y))
print(x%y)

[1 0 1 1 0 1]
[1 0 1 1 0 1]


## Miscellaneous

Q27. If an element of x is smaller than 3, replace it with 3.
And if an element of x is bigger than 7, replace it with 7.

In [95]:
x = np.arange(10)
print(x)
replace_lst = []
for i in x:
    if i<3:
        i=3
    elif i>7:
        i=7
    replace_lst.append(i)
x = np.array(replace_lst)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[3 3 3 3 4 5 6 7 7 7]


Q28. Compute the square of x, element-wise.

In [103]:
x = np.array([1, 2, -1])
print(f'square of x : {np.square(x)}')

square of x : [1 4 1]


Q29. Compute square root of x element-wise.


In [104]:
x = np.array([1., 4., 9.])
print(f'squareroot of x : {np.sqrt(x)}')

squareroot of x : [1. 2. 3.]


Q30. Compute the absolute value of x.

In [107]:
x = np.array([[1, -1], [3, -3]])
print(f'absolute value of x :\n{np.abs(x)}')

absolute value of x :
[[1 1]
 [3 3]]


Q31. Compute an element-wise indication of the sign of x, element-wise.

In [109]:
x = np.array([1, 3, 0, -1, -3])
print(f'sign indication of the sign of x : {np.sign(x)}')

sign indication of the sign of x : [ 1  1  0 -1 -1]
